--- 
env:
  variables:
    CMK_ARN: "arn:aws:kms:eu-central-1:272748214518:key/c33f87a6-bb04-4342-9575-50eb2f834638"
    DEPLOY_REGION: eu-central-1
    S3_BUCKET: axap-aws-ci-cd-artifacts
phases:
  build:
    commands:
      - "export TIMESTAMP=$(date +%s)"
      - "zip -r application-icg-cn-crossaccount-roles.zip application-icg-cn-crossaccount-roles"
      - "mv application-icg-cn-crossaccount-roles.zip application-icg-cn-crossaccount-roles/application-icg-cn-crossaccount-roles.zip"
  install:
    commands:
      - ls
      - pip install --upgrade --quiet pip
      - pip install --upgrade --quiet boto3
      - pip install --upgrade awscli
      - npm i -g @mhlabs/cfn-diagram
      - ls
    pre_build:
      commands:
      - AWS_REGION=DEPLOY_REGION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_VERSION=${COMMIT_HASH}
  post_build:
    commands:
      - cfn-dia html -t application-icg-cn-crossaccount-roles/template.yml -o application-icg-cn-crossaccount-roles
      - zip -r application-icg-cn-foundations.zip ./
      - python post.py application-icg-cn-foundations.zip
      - "echo \"Finished deploying\""
    
version: 0.2